package com.tiooooo.fintrack.component.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3B82F6) // Biru startup
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDEBFF)
val onPrimaryContainerLight = Color(0xFF102C57)

val secondaryLight = Color(0xFF10B981) // Emerald modern
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2FADF)
val onSecondaryContainerLight = Color(0xFF085F3D)

val tertiaryLight = Color(0xFF6366F1) // Indigo techy
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E7FF)
val onTertiaryContainerLight = Color(0xFF1E1B4B)

val errorLight = Color(0xFFEF4444) // Coral soft
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFE4E0)
val onErrorContainerLight = Color(0xFF7A1C1C)

val backgroundLight = Color(0xFFF9FAFB)
val onBackgroundLight = Color(0xFF111827)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF111827)
val surfaceVariantLight = Color(0xFFE5E7EB)
val onSurfaceVariantLight = Color(0xFF374151)

val outlineLight = Color(0xFF9CA3AF)
val outlineVariantLight = Color(0xFFE5E7EB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1F2937)
val inverseOnSurfaceLight = Color(0xFFF3F4F6)
val inversePrimaryLight = Color(0xFF60A5FA)
val surfaceDimLight = Color(0xFFE5E7EB)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5F9)
val surfaceContainerLight = Color(0xFFE2E8F0)
val surfaceContainerHighLight = Color(0xFFD1D5DB)
val surfaceContainerHighestLight = Color(0xFFCBD5E1)

val primaryLightMediumContrast = Color(0xFF003F21)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF007E46)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF0E3E23)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF497757)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF02259A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4D63D3)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FBF2)
val onBackgroundLightMediumContrast = Color(0xFF161D18)
val surfaceLightMediumContrast = Color(0xFFF4FBF2)
val onSurfaceLightMediumContrast = Color(0xFF0C130E)
val surfaceVariantLightMediumContrast = Color(0xFFD8E6D8)
val onSurfaceVariantLightMediumContrast = Color(0xFF2D392F)
val outlineLightMediumContrast = Color(0xFF49564B)
val outlineVariantLightMediumContrast = Color(0xFF637065)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B322C)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEBF3E9)
val inversePrimaryLightMediumContrast = Color(0xFF5BDE91)
val surfaceDimLightMediumContrast = Color(0xFFC1C8C0)
val surfaceBrightLightMediumContrast = Color(0xFFF4FBF2)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEEF6EC)
val surfaceContainerLightMediumContrast = Color(0xFFE3EAE1)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DFD6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCCD4CB)

val primaryLightHighContrast = Color(0xFF00341A)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00552E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF01341A)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF245235)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF001D82)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF233DAD)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF4FBF2)
val onBackgroundLightHighContrast = Color(0xFF161D18)
val surfaceLightHighContrast = Color(0xFFF4FBF2)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD8E6D8)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF232F26)
val outlineVariantLightHighContrast = Color(0xFF3F4C42)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B322C)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF5BDE91)
val surfaceDimLightHighContrast = Color(0xFFB3BBB2)
val surfaceBrightLightHighContrast = Color(0xFFF4FBF2)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEBF3E9)
val surfaceContainerLightHighContrast = Color(0xFFDDE5DB)
val surfaceContainerHighLightHighContrast = Color(0xFFCFD6CE)
val surfaceContainerHighestLightHighContrast = Color(0xFFC1C8C0)

val primaryDark = Color(0xFF60A5FA)
val onPrimaryDark = Color(0xFF0B1E3C)
val primaryContainerDark = Color(0xFF1D4ED8)
val onPrimaryContainerDark = Color(0xFFDCEBFF)

val secondaryDark = Color(0xFF34D399)
val onSecondaryDark = Color(0xFF042F1B)
val secondaryContainerDark = Color(0xFF065F46)
val onSecondaryContainerDark = Color(0xFFBBF7D0)

val tertiaryDark = Color(0xFF8B5CF6)
val onTertiaryDark = Color(0xFF290C5F)
val tertiaryContainerDark = Color(0xFF5B21B6)
val onTertiaryContainerDark = Color(0xFFEDE9FE)

val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF4C1D1D)
val errorContainerDark = Color(0xFF991B1B)
val onErrorContainerDark = Color(0xFFFFE4E0)

val backgroundDark = Color(0xFF111827)
val onBackgroundDark = Color(0xFFE5E7EB)
val surfaceDark = Color(0xFF1F2937)
val onSurfaceDark = Color(0xFFD1D5DB)
val surfaceVariantDark = Color(0xFF374151)
val onSurfaceVariantDark = Color(0xFFC7D2FE)

val outlineDark = Color(0xFF6B7280)
val outlineVariantDark = Color(0xFF4B5563)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E7EB)
val inverseOnSurfaceDark = Color(0xFF1F2937)
val inversePrimaryDark = Color(0xFF3B82F6)
val surfaceDimDark = Color(0xFF1E293B)
val surfaceBrightDark = Color(0xFF374151)
val surfaceContainerLowestDark = Color(0xFF0F172A)
val surfaceContainerLowDark = Color(0xFF1E293B)
val surfaceContainerDark = Color(0xFF273443)
val surfaceContainerHighDark = Color(0xFF374151)
val surfaceContainerHighestDark = Color(0xFF4B5563)

val primaryDarkMediumContrast = Color(0xFF72F5A5)
val onPrimaryDarkMediumContrast = Color(0xFF002D15)
val primaryContainerDarkMediumContrast = Color(0xFF00A65F)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB6E8C2)
val onSecondaryDarkMediumContrast = Color(0xFF002D15)
val secondaryContainerDarkMediumContrast = Color(0xFF6C9B79)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD6DAFF)
val onTertiaryDarkMediumContrast = Color(0xFF001972)
val tertiaryContainerDarkMediumContrast = Color(0xFF7288FA)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1510)
val onBackgroundDarkMediumContrast = Color(0xFFDDE5DB)
val surfaceDarkMediumContrast = Color(0xFF0E1510)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3D4A40)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD2E0D2)
val outlineDarkMediumContrast = Color(0xFFA8B6A8)
val outlineVariantDarkMediumContrast = Color(0xFF869487)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE5DB)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252C26)
val inversePrimaryDarkMediumContrast = Color(0xFF00532D)
val surfaceDimDarkMediumContrast = Color(0xFF0E1510)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4640)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040905)
val surfaceContainerLowDarkMediumContrast = Color(0xFF181F1A)
val surfaceContainerDarkMediumContrast = Color(0xFF232A24)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D342E)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF383F39)

val primaryDarkHighContrast = Color(0xFFBEFFCF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF56DA8D)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F05)
val secondaryDarkHighContrast = Color(0xFFC9FCD5)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF9DCEA9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F05)
val tertiaryDarkHighContrast = Color(0xFFEFEEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB5BFFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000630)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E1510)
val onBackgroundDarkHighContrast = Color(0xFFDDE5DB)
val surfaceDarkHighContrast = Color(0xFF0E1510)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4A40)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE5F4E5)
val outlineVariantDarkHighContrast = Color(0xFFB8C6B9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE5DB)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00532D)
val surfaceDimDarkHighContrast = Color(0xFF0E1510)
val surfaceBrightDarkHighContrast = Color(0xFF4B524B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A211C)
val surfaceContainerDarkHighContrast = Color(0xFF2B322C)
val surfaceContainerHighDarkHighContrast = Color(0xFF363D37)
val surfaceContainerHighestDarkHighContrast = Color(0xFF414942)

val ShimmerLightGray = Color(0xFFF1F1F1)
val ShimmerMediumGray = Color(0xFFE3E3E3)
val ShimmerDarkGray = Color(0xFF1D1D1D)

val dividerColor = Color(0xFFEAEEEE)
val strokeTextField = Color(0xFFDEE1EE)

val onLightBackground = Color(0xFFF3F5FA)

val buttonPrimaryColor = Color(0xFF0C51EF)
val buttonPrimaryTextColor = Color(0xFFFFFFFF)

val buttonSecondaryColor = Color(0xFFE2EBFA)
val buttonSecondaryTextColor = Color(0xFF0C51EF)

val buttonDisableColor = Color(0xFFDEE4EC)
val buttonDisableTextColor = Color(0xFFAFB5D3)
